#!/bin/bash

while true
do
    echo "--- Simple Calculator ---"
    echo "1. Addition"
    echo "2. Subtraction"
    echo "3. Multiplication"
    echo "4. Division"
    echo "5. Exit"

    read choice

    if [ $choice -eq 5 ]
    then
        echo "Exiting..."
        break
    fi

    echo "Enter first number:"
    read a
    echo "Enter second number:"
    read b

    case $choice in
        1) echo "Addition = $((a + b))" ;;
        2) echo "Subtraction = $((a - b))" ;;
        3) echo "Multiplication = $((a * b))" ;;
        4) 
            if [ $b -eq 0 ]
            then
                echo "Error: Division by zero"
            else
                echo "Division = $((a / b))"
            fi
            ;;
        *) echo "Invalid choice" ;;
    esac
done
